name: kilometer_diary
description: Store your kilometers and calculate total distance
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  path: ^1.8.2
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/kilometer_diary_logo.png"